
pipeline{
    agent any
    stages{

        stage ('Permission') {
            steps{
                sh 'cd build-and-launch && chmod +x build-and-launch.sh'
            }
        }
        stage('Build-and-Launch'){
            steps{
                sh 'cd build-and-launch && sh build-and-launch.sh'
            }
        }
    }     
}